name: foo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.8
  firebase_analytics: ^12.1.1
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  flutter_mobx: ^2.3.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  hive: ^2.2.3
  mobx: ^2.6.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.10.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.6
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - assets/images/
